chat/urls.py
from django.urls import path, re_path


from .views import ThreadView, inbox_view, message_box_list, get_comments, get_comments_renew

app_name = 'chat'
urlpatterns = [
    path("", inbox_view, name='inbox'),
    path("message-box-list", message_box_list, name='message-box-list'),
    path("get-comments-list/<uuid_id>",get_comments,name='get-comments-list'),
    path("get-comments-list-renew/<uuid_id>",get_comments_renew,name='get-comments-renew-list'),
    re_path(r"^(?P<uuid_id>[\w.@+-]+)", ThreadView.as_view(),name='message-box-detail'),
    # re_path(r"^get-comments-list/(?P<uuid_id>[\w.@+-]+)", get_comments,name='get-comments-list'),
]

userprofile/urls.py
from django.urls import path

from userprofile.views import *

app_name = 'userprofile'

urlpatterns = [
	path('', feed, name='feed'),
	path('', feed, name='dashboard'),
	path('photo-upload/', photo_upload, name='photo-upload'),
	path('page/<slug>/', staticpage_detail, name='static-page-detail'),
	path('get-photo-profile/<type>/', get_photo_profile, name='get-photo-profile'),
	# path('profile/', profile, name='profile'),
	# path('profile/<slug>', profile_tab, name='profile-tab'),
	path('v/<id>/', profile_v, name='profile-v'),
	path('v/<id>/change/', profile_v_change, name='profile-v-change'),
	path('general-post-change/', general_post_change, name='general-post-change'),
	path('v/<id>/<slug>', profile_tab, name='profile-tab-v'),
	path('settings/<slug>', settings_page, name='settings'),
	path('experience-andeducation-create/<slug>', experience_andeducation_create, name='experience-andeducation-create'),
	path('experience-andeducation-list/<slug>', experience_andeducation_list, name='experience-andeducation-list'),
	path('post-share/', post_share, name='post-share'),
	path('post-remove/<id>/', post_remove, name='post-remove'),

	path('like-save/<int:id>/<slug>/', like_save, name='like-save-post'),



	path('friend-list/<slug>', friend_list, name='friend-list'),
	# path('projects-form/', projects_form, name='projects-form'),
	path('notifications-list/', notifications_list, name='notifications-list'),
	path('message-notification-show/<slug>/', message_notification_show, name='message-notification-show'),
	path('notification-remove/<id>/', notification_remove, name='notification-remove'),
	path('users-list/', users_list, name='users-list'),
	path('event-list/<slug>/', event_list, name='event-list'),
	path('news-list/<slug>/', blognews_list, name='blognews-list'),
	path('friend-list/<slug>/', friend_list, name='friend-list'),
	path('all-sections/', all_sections, name='all-sections'),
	path('all-sections/section-<int:id>/', section_item, name='section-item'),
	path('all-sections/section-<int:id>/parent-<int:p_id>/', tutorials, name='section-item-parent'),
	path('all-sections/tutorial-<int:id>/', article_item, name='tutorial-item'),

	path('projects-list/', projects_list, name='projects-list'),
	path('projects/create/', projects_create, name='projects-create'),
	path('projects/edit/<int:id>/', projects_edit, name='projects-edit'),
	path('projects/view/<int:id>/', projects_view, name='projects-view'),

	path('events-list/', events_list, name='events-list'),
	path('events/view/<int:id>/', events_view, name='events-view'),
	path('news-list/', news_list, name='news-list'),
	path('news/edit/<int:id>/', projects_edit, name='news-view'),


 ]

templates/home/include/_sidebar-user-list.html
{% load static %}
{% load i18n %}

<div class="ui-block">
    <div class="ui-block-title">
        <h6 class="title">{{ title }}</h6>
    </div>
    <div class="ui-block-content">

        <!-- W-Faved-Page -->

        <ul class="widget w-faved-page js-zoom-gallery">
            {% for data_list_item in data_list %}
                <li>
                    <a href="{% url 'userprofile:profile-v' data_list_item.uuid_id %}">
                        <img src="{% static 'local/app/img/avatar38-sm.jpg' %}" alt="author">
                    </a>
                </li>
            {% endfor %}
            <li class="all-users">
                <a href="{% url 'userprofile:users-list' %}">+</a>
            </li>
        </ul>

        <!-- .. end W-Faved-Page -->
    </div>
</div>

templates/home/include/list-item.html
{% load static %}

<div class="ui-block">

    <div class="birthday-item inline-items badges">
        <div class="author-thumb">
            <a href="{% url 'userprofile:tutorial-item' data_item.id %}" class="h6 author-name">
                <img src="{% static 'local/app/img/badge1.png' %}" alt="author">
            </a>
        </div>
        <div class="birthday-author-name">
            <a href="{% url 'userprofile:tutorial-item' data_item.id %}" class="h6 author-name">{{ data_item.title }}</a>
            <div class="birthday-date">
                {{ data_item.short_title }}
            </div>
        </div>

        <div class="skills-item">
            <a href="{% url 'userprofile:tutorial-item' data_item.id %}" class="h6 author-name">
                {{ data_item.created_date }}
            </a>
        </div>

    </div>

</div>

templates/home/include/user-item.html
{% load static %}
{% load i18n %}
{% load django_follow_system_tags %}

<div class="col col-xl-3 col-lg-6 col-md-6 col-sm-6 col-12">
    <div class="ui-block">
        <!-- Friend Item -->
        <div class="friend-item">
            <div class="friend-header-thumb">
                <img src="{% static 'local/app/img/friend1.jpg' %}" alt="friend">
            </div>

            <div class="friend-item-content">
                <div class="friend-avatar">
                    <div class="author-thumb">
                        <a href="{% url 'userprofile:profile-v' data_item.uuid_id %}">
                            <img src="{% static 'local/app/img/default-user.jpg' %}" style="width: 92px;" alt="author">
                        </a>
                    </div>
                    <div class="author-content">
                        <a href="{% url 'userprofile:profile-v' data_item.uuid_id %}" class="h5 author-name">{{ data_item.get_full_name }}</a>
                        <div class="country">{{ data_item.get_user_type }}</div>
                    </div>
                </div>

                <div class="swiper-container" data-slide="fade">
                    <div class="swiper-wrapper">
                        <div class="swiper-slide">
                            <div class="friend-count" data-swiper-parallax="-500">
                                <a href="#" class="friend-count-item">
                                    <div class="h6">0</div>
                                    <div class="title">{% trans 'Izləyicilər' %}</div>
                                </a>
                                <a href="#" class="friend-count-item">
                                    <div class="h6">0</div>
                                    <div class="title">{% trans 'Posts' %}</div>
                                </a>
                            </div>
                            <div class="control-block-button" data-swiper-parallax="-100">
                                <a href="javascript:void(0)" class="btn btn-control follow-op {% if True %}bg-primary{% else %}bg-blue{% endif %}">
                                    <svg class="olymp-happy-face-icon"><use xlink:href="{% static 'local/app/svg-icons/sprites/icons.svg' %}#olymp-happy-face-icon"></use></svg>
                                </a>

                                <a href="{% url 'chat:message-box-detail' data_item.uuid_id %}" class="btn btn-control bg-purple">
                                    <svg class="olymp-chat---messages-icon"><use xlink:href="{% static 'local/app/svg-icons/sprites/icons.svg' %}#olymp-chat---messages-icon"></use></svg>
                                </a>

                            </div>
                        </div>
                    </div>

                    <!-- If we need pagination -->
                    <div class="swiper-pagination"></div>
                </div>
            </div>
        </div>
        <!-- ... end Friend Item -->
    </div>
</div>