chat/urls.py
from django.urls import path, re_path


from .views import ThreadView, inbox_view, message_box_list, get_comments, get_comments_renew

app_name = 'chat'
urlpatterns = [
    path("", inbox_view, name='inbox'),
    path("message-box-list", message_box_list, name='message-box-list'),
    path("get-comments-list/<uuid_id>",get_comments,name='get-comments-list'),
    path("get-comments-list-renew/<uuid_id>",get_comments_renew,name='get-comments-renew-list'),
    re_path(r"^(?P<uuid_id>[\w.@+-]+)", ThreadView.as_view(),name='message-box-detail'),
    # re_path(r"^get-comments-list/(?P<uuid_id>[\w.@+-]+)", get_comments,name='get-comments-list'),
]

userprofile/urls.py
from django.urls import path

from userprofile.views import *

app_name = 'userprofile'

urlpatterns = [
	path('', feed, name='feed'),
	path('', feed, name='dashboard'),
	path('photo-upload/', photo_upload, name='photo-upload'),
	path('page/<slug>/', staticpage_detail, name='static-page-detail'),
	path('get-photo-profile/<type>/', get_photo_profile, name='get-photo-profile'),
	# path('profile/', profile, name='profile'),
	# path('profile/<slug>', profile_tab, name='profile-tab'),
	path('v/<id>/', profile_v, name='profile-v'),
	path('v/<id>/change/', profile_v_change, name='profile-v-change'),
	path('general-post-change/', general_post_change, name='general-post-change'),
	path('v/<id>/<slug>', profile_tab, name='profile-tab-v'),
	path('settings/<slug>', settings_page, name='settings'),
	path('experience-andeducation-create/<slug>', experience_andeducation_create, name='experience-andeducation-create'),
	path('experience-andeducation-list/<slug>', experience_andeducation_list, name='experience-andeducation-list'),
	path('post-share/', post_share, name='post-share'),
	path('post-remove/<id>/', post_remove, name='post-remove'),

	path('like-save/<int:id>/<slug>/', like_save, name='like-save-post'),



	path('friend-list/<slug>', friend_list, name='friend-list'),
	# path('projects-form/', projects_form, name='projects-form'),
	path('notifications-list/', notifications_list, name='notifications-list'),
	path('message-notification-show/<slug>/', message_notification_show, name='message-notification-show'),
	path('notification-remove/<id>/', notification_remove, name='notification-remove'),
	path('users-list/', users_list, name='users-list'),
	path('event-list/<slug>/', event_list, name='event-list'),
	path('news-list/<slug>/', blognews_list, name='blognews-list'),
	path('friend-list/<slug>/', friend_list, name='friend-list'),
	path('all-sections/', all_sections, name='all-sections'),
	path('all-sections/section-<int:id>/', section_item, name='section-item'),
	path('all-sections/section-<int:id>/parent-<int:p_id>/', tutorials, name='section-item-parent'),
	path('all-sections/tutorial-<int:id>/', article_item, name='tutorial-item'),

	path('projects-list/', projects_list, name='projects-list'),
	path('projects/create/', projects_create, name='projects-create'),
	path('projects/edit/<int:id>/', projects_edit, name='projects-edit'),
	path('projects/view/<int:id>/', projects_view, name='projects-view'),

	path('events-list/', events_list, name='events-list'),
	path('events/view/<int:id>/', events_view, name='events-view'),
	path('news-list/', news_list, name='news-list'),
	path('news/edit/<int:id>/', projects_edit, name='news-view'),


 ]

userprofile/models.py
from django.conf import settings
from django.db import models

# Create your models here.
from django.conf import settings
from django.contrib.auth.models import User
from django.db import models
from django.db.models.signals import m2m_changed, post_save
from django.db.utils import IntegrityError
from django.dispatch import receiver

from django.db import models

class Photo(models.Model):
    # user = models.ForeignKey(settings.AUTH_USER_MODEL,related_name="+",on_delete=models.CASCADE)
    image = models.ImageField()
    description = models.CharField(max_length=255, blank=True)
    uploaded_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name = 'photo'
        verbose_name_plural = 'photos'

#
# class Follow(models.Model):
#     user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE,related_query_name='follow')
#     following = models.ManyToManyField(
#         settings.AUTH_USER_MODEL, blank=True, related_name="following"
#     )
#     created = models.DateTimeField(auto_now_add=True)
#
#     @property
#     def username(self):
#         return str(self.user)
#
#     @property
#     def follower(self):
#         return self.__class__.objects.filter(following=self.user.id)
#
#     def is_follow(self, other_user):
#         return bool(
#             self.__class__.objects.filter(user=self.user).filter(
#                 following=other_user.id
#             )
#         )
#
#
# @receiver(post_save, sender=User)
# def create_user_follow(sender, instance, created, **kwargs):
#     if created:
#         Follow(user=instance).save()
#
#
# @receiver(m2m_changed, sender=Follow.following.through)
# def verify_follow_m2m(sender, **kwargs):
#     oiou = kwargs.get("instance", None)
#     action = kwargs.get("action", None)
#     following = kwargs.get("pk_set", None)
#     if action == "pre_add":
#         for following_user_id in following:
#             if following_user_id == oiou.user.id:
#                 raise IntegrityError("Can not be follow yourself")
#             elif Follow.objects.filter(user=oiou.user).filter(
#                 following=following_user_id
#             ):
#                 raise IntegrityError(
#                     f"Follow with user {oiou.user}\
#                       already exists for publisher {Follow.objects.get(user=oiou.user)}"
#                 )

userprofile/views.py
import hashlib
import random

from django.forms import inlineformset_factory
from django.views import View

from django.contrib import messages
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
from django.contrib.auth.hashers import make_password
from django.db.models import Q
from django.http import JsonResponse, Http404
from django.shortcuts import render, get_object_or_404

from django.utils.translation import ugettext as _
# Create your views here.
from django.template.loader import render_to_string
from django.utils import timezone

from base_user.tools.common import USERTYPESSEARCH
from chat.models import Thread
from content.forms import ProjectModelForm
from content.models import *
from general.views import base_auth
from userprofile.forms import *

GUser = get_user_model()

@login_required(login_url='base-user:login')
def photo_upload(request):
    context = base_auth(req=request)
    photos = Photo.objects.all()
    if request.method == 'POST':
        form = PhotoForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            # return redirect('photo_list')
    else:
        form = PhotoForm()
    context['form'] = form
    return render(request, 'userprofile/photo/profile.html', context)

@login_required(login_url='base-user:login')
def feed(request):
    now = datetime.datetime.now()
    user = request.user
    context = base_auth(req=request)

    context['post_share_form'] = PostShareForm(request.POST or None)
    if request.method == 'POST' and request.is_ajax():
        try:
            page_num = int(request.POST.get('post-page-num', 1))
        except:
            page_num = 0
        try:
            loaded_post_count = int(request.POST.get('loaded-post-count', 1))
        except:
            loaded_post_count = 0
        posts = SharedPost.objects.filter().order_by('-id')

        user_liked = SharedPostLike.objects.filter(user=user).values_list('post_id',flat=True)
        posts = posts[50 * (page_num - 1) + loaded_post_count:50 * page_num + loaded_post_count]
        list_html = ''
        last_item  = None
        for_i = 0
        for item in posts:
            if for_i == 0 and page_num == 1:
                last_item = item
            for_i +=1
            list_html = "{}{}".format(list_html, render_to_string(
                "home/include/post/post-item.html",
                {
                    "post_liked": True if item.id in user_liked else False,
                    "item": item,
                    "me": True if request.user == item.user else False,
                }))
        data = {
            'main_result':list_html,
            'date_time':last_item.id if last_item else 0,
        }
        return JsonResponse(data=data)
    context['last_events'] =  Event.objects.filter()[:10]
    context['last_blogs'] =  BlogNews.objects.filter()[:10]
    return render(request, 'home/index.html', context=context)


@login_required(login_url='base-user:login')
def post_share(request):
    now = datetime.datetime.now()
    context = base_auth(req=request)
    user = request.user
    form = PostShareForm(request.POST or None,request.FILES or None)
    if request.method == 'POST' and  request.is_ajax():
        message_code = 0
        message = 0
        if form.is_valid():
            cleaned_data = form.cleaned_data
            text = cleaned_data.get('text',None)
            data_item = SharedPost(content=text,user=user)
            data_item.save()
            message_code = 1
            message = 'Uğurlu'
        else:
            message = " , ".join([v[0].__unicode__() for k, v in form.errors.items()])

        data = {
            'code':message_code,
            'result':message,
        }
        return JsonResponse(data=data)

    else:
        raise Http404


@login_required(login_url='base-user:login')
def like_save(request,id,slug):
    now = datetime.datetime.now()
    context = base_auth(req=request)
    user = request.user
    form = PostShareForm(request.POST or None,request.FILES or None)

    if request.method == 'POST' and  request.is_ajax():
        message_code = 0
        message = 0
        liked_count = 0
        saved_count = 0
        if slug == 'liked':
            try:
                data_item = SharedPostLike.objects.filter(user=user,post_id=id).get()
                data_item.delete()
                data_item.post.liked_count = data_item.post.liked_count - 1
                data_item.post.save()
                message_code = 2
            except:
                try:
                    data_item = SharedPostLike.objects.create(user=user,post_id=id)
                    data_item.post.liked_count = data_item.post.liked_count + 1
                    data_item.post.save()
                    message_code = 1
                    saved_count = data_item.post.saved_count
                    liked_count = data_item.post.liked_count
                except:
                    pass
            data = {
                'code':message_code,
                'saved_count':saved_count,
                'liked_count':liked_count,
            }
            return JsonResponse(data=data)
        else:
            raise Http404


    else:
        raise Http404


def staticpage_detail(request,slug):
    now = datetime.datetime.now()
    context = base_auth(req=request)

    # return '\n'.join(url.format(year) for year in range(2000, 2016))
    context['data_item'] =  get_object_or_404(StaticPage,key_page=slug)
    # context['mac_address'] =  Package.objects.filter(status__in=['active','waiting']).count()
    return render(request, 'home/page.html', context=context)


@login_required(login_url='base-user:login')
def profile(request):
    now = datetime.datetime.now()
    context = base_auth(req=request)
    user = request.user

    # return '\n'.join(url.format(year) for year in range(2000, 2016))
    # context['mac_address'] =  ':'.join(("%012X" % mac)[i:i+2] for i in range(0, 12, 2))
    # context['mac_address'] =  Package.objects.filter(status__in=['active','waiting']).count()
    context['uud_id'] = user.uuid_id
    return render(request, 'userprofile/dashboard.html', context=context)


@login_required(login_url='base-user:login')
def profile_v(request,id):
    now = datetime.datetime.now()
    context = base_auth(req=request)
    user = get_object_or_404(GUser,uuid_id=id)
    current_user_ch = False
    if str(request.user.uuid_id) == id:
        current_user_ch = True
    context['uud_id'] = id


    if request.method == 'POST' and request.is_ajax():
        try:
            page_num = int(request.POST.get('post-page-num', 1))
        except:
            page_num = 0
        try:
            loaded_post_count = int(request.POST.get('loaded-post-count', 1))
        except:
            loaded_post_count = 0
        posts = SharedPost.objects.filter(user=user).order_by('-id')

        user_liked = SharedPostLike.objects.filter(user=user).values_list('post_id',flat=True)
        posts = posts[50 * (page_num - 1) + loaded_post_count:50 * page_num + loaded_post_count]
        list_html = ''
        last_item  = None
        for_i = 0
        for item in posts:
            if for_i == 0 and page_num == 1:
                last_item = item
            for_i +=1
            list_html = "{}{}".format(list_html, render_to_string(
                "home/include/post/post-item.html",
                {
                    "post_liked": True if item.id in user_liked else False,
                    "item": item,
                    "me": True if request.user == item.user else False,
                }))
        data = {
            'main_result':list_html,
            'extra_count':posts.count(),
            'date_time':last_item.id if last_item else 0,
        }
        return JsonResponse(data=data)
    # return '\n'.join(url.format(year) for year in range(2000, 2016))
    # context['mac_address'] =  ':'.join(("%012X" % mac)[i:i+2] for i in range(0, 12, 2))
    # context['mac_address'] =  Package.objects.filter(status__in=['active','waiting']).count()
    context['user_profile'] = user
    context['current_user_ch'] = current_user_ch
    context['post_share_form'] = PostShareForm(request.POST or None)
    return render(request, 'userprofile/dashboard.html', context=context)


@login_required(login_url='base-user:login')
def post_remove(request,id):
    now = datetime.datetime.now()
    context = base_auth(req=request)
    user = request.user
    current_user_ch = False
    if request.method == 'POST' and request.is_ajax():
        try:
            post_item = SharedPost.objects.get(id=id,user=user)
            post_item.delete()
            code = 1
        except:
            code = 0
        data = {
            'code' : code,
        }
        return JsonResponse(data)
    else:
        raise Http404

@login_required(login_url='base-user:login')
def profile_v_change(request,id):
    now = datetime.datetime.now()
    context = base_auth(req=request)
    user = get_object_or_404(GUser,uuid_id=id)
    current_user_ch = False
    if str(request.user.uuid_id) == id:
        pass
    context['uud_id'] = id



    if request.method == 'POST' and request.is_ajax():
        list_html = ''
        date_time = -1
        extra_count = 0
        try:
            try:
                date_time = request.POST.get('date_time', 1)
            except:
                date_time = -1
            posts = SharedPost.objects.filter(id__gt=date_time).order_by('-id')

            if posts:
                code = 1
                extra_count = posts.count()
                user_liked = SharedPostLike.objects.filter(post_id__in=posts.values_list('id',flat=True)).filter(user=user).values_list('post_id',flat=True)
                last_item  = None
                for_i = 0
                if posts:
                    for item in posts:
                        if for_i == 0:

templates/userprofile/profile-tab.html
{% extends 'main-base.html' %}
{% load static from staticfiles %}
{% load i18n %}
{% block content_block %}

    <div class="container" xmlns:xlink="">
        <div class="row">
            <div class="col col-xl-12 col-lg-12 col-md-12 col-sm-12 col-12">
                <div class="ui-block">
                    <div class="top-header">
                        <div class="top-header-thumb">
                            <img src="{% static 'local/app/img/top-header1.jpg' %}" alt="nature">
                        </div>
                        <div class="profile-section">
                            <div class="row">
                                <div class="col col-lg-5 col-md-5 col-sm-12 col-12">
                                    <ul class="profile-menu">
                                        <li>
                                            <a href="{% url 'userprofile:profile-v' uud_id %}" >{% trans 'Timeline' %}</a>
                                        </li>
                                        <li>
                                            <a href="{% url 'userprofile:profile-tab-v' uud_id 'about' %}" {% if slug == 'about' %} class="active"{% endif %}>{% trans 'About' %}</a>
                                        </li>
                                    </ul>
                                </div>
                                <div class="col col-lg-5 ml-auto col-md-5 col-sm-12 col-12">
                                    <ul class="profile-menu">
                                        <li>
                                            <a href="{% url 'userprofile:profile-tab-v' uud_id 'education' %}" {% if slug == 'education' %} class="active"{% endif %}>{% trans 'Education' %}</a>
                                        </li>
                                        <li>
                                            <a href="{% url 'userprofile:profile-tab-v' uud_id 'expreience' %}" {% if slug == 'expreience' %} class="active"{% endif %}>{% trans 'Expreience' %}</a>
                                        </li>
                                    </ul>
                                </div>
                            </div>

                            <div class="control-block-button">
                                {% if current_user_ch %}
                                    <div class="btn btn-control bg-primary more">
                                        <svg class="olymp-settings-icon"><use xlink:href="{% static 'local/app/svg-icons/sprites/icons.svg' %}#olymp-settings-icon"></use></svg>

                                        <ul class="more-dropdown more-with-triangle triangle-bottom-right">
                                            <li>
                                                <a href="#" data-toggle="modal" data-target="#update-header-photo">{% trans 'Update Profile Photo' %}</a>
                                            </li>
                                            <li>
                                                <a href="#" data-toggle="modal" data-target="#update-header-photo">{% trans 'Update Header Photo' %}</a>
                                            </li>
                                            <li>
                                                <a href="{% url 'userprofile:settings' 'profile' %}">{% trans 'Account Settings' %}</a>
                                            </li>
                                        </ul>
                                    </div>
                                {% else %}
                                    <a href="javascript:void(0)" class="btn btn-control bg-blue">
                                        <svg class="olymp-happy-face-icon"><use xlink:href="{% static 'local/app/svg-icons/sprites/icons.svg' %}#olymp-happy-face-icon"></use></svg>
                                    </a>

                                    <a href="#" class="btn btn-control bg-purple">
                                        <svg class="olymp-chat---messages-icon"><use xlink:href="{% static 'local/app/svg-icons/sprites/icons.svg' %}#olymp-chat---messages-icon"></use></svg>
                                    </a>
                                {% endif %}
                            </div>
                        </div>
                        <div class="top-header-author">
                            <a href="javascript:void(0);" class="author-thumb">
                                <img src="{% static 'local/app/img/default-user.jpg' %}" alt="author" xlink:height="124" style="height: 124px"/>
                            </a>
                            <div class="author-content">
                                <a href="javascript:void(0);" class="h4 author-name">
                                    {{ user_profile.get_full_name }}
                                </a>
{#                                <div class="country">San Francisco, CA</div>#}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- ... end Top Header-Profile -->
    <div class="container">
        <div class="row">

            <!-- Main Content -->

            <div class="col col-xl-9 order-xl-2 col-lg-12 order-lg-1 col-md-12 col-sm-12 col-12" id="newsfeed-items-grid">

                <div class="ui-block responsive-flex">
                    <div class="ui-block-title">
                        <div class="h3 title text-center">{{ page_title }}</div>
                    </div>
                </div>

                {% autoescape off %}
                    {{ result_data }}
                {% endautoescape %}
            </div>

            <!-- ... end Main Content -->


            <!-- Left Sidebar -->

            <div class="col col-xl-3 order-xl-1 col-lg-6 order-lg-2 col-md-6 col-sm-6 col-12">

                <div class="ui-block">
                    <div class="ui-block-title">
                        <h6 class="title">{% trans 'Profile Intro' %}</h6>
                    </div>
                    <div class="ui-block-content">

                        <!-- W-Personal-Info -->

                        <ul class="widget w-personal-info item-block">
                            <li>
                                <span class="title">{% trans 'About' %}:</span>
                                <span class="text">
                                    {% if user_profile.about %}
                                        {{ user_profile.about|slice:'100' }}
                                    {% endif %}
                                </span>
                            </li>
                        </ul>

                        <!-- .. end W-Personal-Info -->
                        <!-- W-Socials -->

                        <div class="widget w-socials">
                            <h6 class="title">{% trans 'Other Social Networks' %}:</h6>
                            {% if user_profile.facebook %}
                                <a target="_blank" href="{{ user_profile.facebook }}" class="social-item bg-facebook">
                                    <i class="fab fa-facebook-f" aria-hidden="true"></i>
                                    Facebook
                                </a>
                            {% endif %}
                            {% if user_profile.linkedin %}
                                <a target="_blank" href="{{ user_profile.facebook }}" class="social-item bg-dribbble">
                                    <i class="fab fa-linkedin-in" aria-hidden="true"></i>
                                    Linkedin
                                </a>
                            {% endif %}
                            {% if user_profile.instagram %}
                                <a target="_blank" href="{{ user_profile.facebook }}" class="social-item bg-twitter">
                                    <i class="fab fa-instagram" aria-hidden="true"></i>
                                    Instagram
                                </a>
                            {% endif %}
                        </div>


                        <!-- ... end W-Socials -->
                    </div>
                </div>

            </div>

            <!-- ... end Left Sidebar -->



        </div>
    </div>

{% endblock %}

templates/userprofile/profile.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>