chat/urls.py
from django.urls import path, re_path


from .views import ThreadView, inbox_view, message_box_list, get_comments, get_comments_renew

app_name = 'chat'
urlpatterns = [
    path("", inbox_view, name='inbox'),
    path("message-box-list", message_box_list, name='message-box-list'),
    path("get-comments-list/<uuid_id>",get_comments,name='get-comments-list'),
    path("get-comments-list-renew/<uuid_id>",get_comments_renew,name='get-comments-renew-list'),
    re_path(r"^(?P<uuid_id>[\w.@+-]+)", ThreadView.as_view(),name='message-box-detail'),
    # re_path(r"^get-comments-list/(?P<uuid_id>[\w.@+-]+)", get_comments,name='get-comments-list'),
]

chat/models.py
import datetime

from django.conf import settings
from django.db import models
from django.db.models import Q
from django.db.models.signals import post_save

# from .utils import broadcast_msg_to_chat, trigger_welcome_message


class ThreadManager(models.Manager):
    def by_user(self, user):
        qlookup = Q(first=user) | Q(second=user)
        qlookup2 = Q(first=user) & Q(second=user)
        qs = self.get_queryset().filter(qlookup).exclude(qlookup2).distinct()
        return qs

    def get_or_new(self, user, other_uuid_id):  # get_or_create
        uuid_id = user.uuid_id
        if uuid_id == other_uuid_id:
            return None
        qlookup1 = Q(first__uuid_id=uuid_id) & Q(second__uuid_id=other_uuid_id)
        qlookup2 = Q(first__uuid_id=other_uuid_id) & Q(second__uuid_id=uuid_id)
        qs = self.get_queryset().filter(qlookup1 | qlookup2).distinct()
        if qs.count() == 1:
            return qs.first(), False
        elif qs.count() > 1:
            return qs.order_by('timestamp').first(), False
        else:
            Klass = user.__class__
            user2 = Klass.objects.get(uuid_id=other_uuid_id)
            if user != user2:
                obj = self.model(
                    first=user,
                    second=user2
                )
                obj.save()
                return obj, True
            return None, False


class Thread(models.Model):
    first = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='chat_thread_first')
    second = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='chat_thread_second')
    updated = models.DateTimeField(auto_now=True)
    last_message = models.ForeignKey('ChatMessage',blank=True,null=True, on_delete=models.SET_NULL,related_name='last_message')
    updated_date = models.DateTimeField(default=datetime.datetime.now())
    timestamp = models.DateTimeField(auto_now_add=True)

    objects = ThreadManager()

    @property
    def room_group_name(self):
        return 'chat_{}'.format(self.id)

    # def broadcast(self, msg=None):
    #     if msg is not None:
    #         broadcast_msg_to_chat(msg, group_name=self.room_group_name, user='admin')
    #         return True
    #     return False


def new_user_receiver(sender, instance, created, *args, **kargs):
    if created:
        # UserKlass = instance.__class__
        # my_admin_user = UserKlass.objects.get(id=1)
        # obj, created = Thread.objects.get_or_new(my_admin_user, instance.username)
        # obj.broadcast(msg='Hello and welcome')

        sender_id = 1  # admin user, main sender
        receiver_id = instance.id
        # trigger_welcome_message(sender_id, receiver_id)


# post_save.connect(new_user_receiver, sender=settings.AUTH_USER_MODEL)


class ChatMessage(models.Model):
    thread = models.ForeignKey(Thread, null=True, blank=True, on_delete=models.SET_NULL)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, verbose_name='sender', on_delete=models.CASCADE)
    seen = models.BooleanField(default=False)
    message = models.TextField()
    timestamp = models.DateTimeField(auto_now_add=True)

def new_message_send(sender, instance, created, *args, **kargs):
    if created:
        instance.thread.last_message = instance
        instance.thread.updated_date = instance.timestamp
        instance.thread.save()

post_save.connect(new_message_send, sender=ChatMessage)

chat/forms.py
from django import forms
from django.utils.translation import ugettext as _


class ComposeForm(forms.Form):
    message = forms.CharField(max_length=5000,label=_('Mesaj'), required=True, widget=forms.Textarea(attrs={ 'autocomplete': 'off','class': 'form-control','rows': '3', }))



class MainSearchForm(forms.Form):
    search_text = forms.CharField(max_length=255,label=_('Axtar'), required=False, widget=forms.TextInput(
        attrs={'placeholder': _('Axtar'), 'autocomplete': 'off',
               'class': 'form-control', }))



class MessageForm(forms.Form):
    message_text = forms.CharField(max_length=5000,label=_('Mesaj'), required=True, widget=forms.Textarea(attrs={ 'autocomplete': 'off','class': 'form-control','rows': '3', }))

chat/views.py
import datetime

from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Q
from django.http import Http404, HttpResponseForbidden, JsonResponse
from django.shortcuts import render
from django.template.loader import render_to_string
from django.urls import reverse
from django.views.generic.edit import FormMixin

from django.views.generic import DetailView, ListView
GUser = get_user_model()

from general.views import base_auth
from .forms import ComposeForm, MainSearchForm, MessageForm
from .models import Thread, ChatMessage


from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import Http404, HttpResponseForbidden
from django.shortcuts import render
from django.urls import reverse
from django.views.generic.edit import FormMixin

from django.views.generic import DetailView, ListView

from .forms import ComposeForm
from .models import Thread, ChatMessage


@login_required(login_url='base-user:login')
def inbox_view(request):
    now = datetime.datetime.now()
    context = base_auth(req=request)

    threads =  Thread.objects.by_user(request.user).exclude(last_message=None)
    # return '\n'.join(url.format(year) for year in range(2000, 2016))
    context['threads'] =  threads
    context['message_box_form'] =  MainSearchForm(request.POST or None)
    return render(request, 'chat/inbox.html', context=context)




@login_required(login_url='base-user:login')
def message_box_list(request,):
    user = request.user
    search_form = MainSearchForm(request.POST or None)

    # return '\n'.join(url.format(year) for year in range(2000, 2016))
    if search_form.is_valid() and request.is_ajax():

        cleaned_data = search_form.cleaned_data
        search_text = cleaned_data.get('search_text',None)
        threads_items_gen = Thread.objects.by_user(request.user).exclude(last_message=None)
        firstname = ''
        lastname = ''
        try:
            firstname = search_text.split(' ')[0]
        except:
            pass
        try:
            lastname = search_text.split(' ')[1]
        except:
            pass
        print("{} - {}".format(firstname,lastname))
        # threads_items = []
        if search_text:
            if firstname:
                if lastname:
                    threads_items = threads_items_gen.filter(Q(Q(first__first_name__icontains=firstname, first__last_name__icontains=lastname) | Q(second__first_name__icontains=firstname, second__last_name__icontains=lastname)) | Q(Q(first__first_name__icontains=lastname, first__last_name__icontains=firstname) | Q(second__first_name__icontains=lastname, second__last_name__icontains=firstname)))
                    # threads_items = threads_items_gen.filter().order_by('-updated_date')
                else:
                    threads_items = threads_items_gen.filter(Q(first__first_name__icontains=firstname) | Q(first__last_name__icontains=firstname) | Q(second__first_name__icontains=firstname) | Q(second__last_name__icontains=firstname)).order_by('-updated_date')
            else:
                threads_items = threads_items_gen.order_by('-updated_date')

        else:
            threads_items = threads_items_gen.order_by('-updated_date')

        try:
            page_num = int(request.POST.get('page-num-message-box', 2))
        except:
            page_num = 0

        threads_items = threads_items[20 * (page_num - 1):20 * page_num]
        list_html = ''
        for item in threads_items:
            is_ssen = True
            if item.last_message:
                if item.last_message.user != user and item.last_message.seen  == False:
                    is_ssen = False
            list_html = "{}{}".format(list_html, render_to_string(
                "chat/include/message-box-item.html",
                {
                    "data_item": item,
                    "is_seen": is_ssen,
                    "to_user": item.second if item.first == request.user else item.first
                }))
        data = {
            'main_result':list_html,
        }

        return JsonResponse(data)



class ThreadView(LoginRequiredMixin, FormMixin, DetailView):
    template_name = 'chat/inbox.html'
    form_class = ComposeForm
    success_url = './'

    def get_queryset(self):
        return Thread.objects.by_user(self.request.user).exclude(last_message=None)

    def get_object(self):
        other_uuid_id  = self.kwargs.get("uuid_id")
        obj, created    = Thread.objects.get_or_new(self.request.user, other_uuid_id)
        if obj == None:
            raise Http404
        return obj

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form'] = self.get_form()
        context['message_box_form'] =  MainSearchForm(self.request.POST or None)
        context['message_form'] =  ComposeForm(self.request.POST or None)
        context.update(base_auth(req=self.request))
        return context

    def post(self, request, *args, **kwargs):
        if not request.user.is_authenticated:
            return HttpResponseForbidden()
        self.object = self.get_object()
        form = self.get_form()
        if form.is_valid():
            return self.form_valid(form)
        else:
            return self.form_invalid(form)

    def form_valid(self, form):
        thread = self.get_object()
        user = self.request.user
        message = form.cleaned_data.get("message")
        ChatMessage.objects.create(user=user, thread=thread, message=message)
        return JsonResponse(data={'code':1})



@login_required(login_url='base-user:login')
def comment_share(request,uuid_id):
    now = datetime.datetime.now()
    context = base_auth(req=request)
    user = request.user
    form = ComposeForm(request.POST or None,request.FILES or None)
    if request.method == 'POST' and  request.is_ajax():
        message_code = 0
        message = 0
        if form.is_valid():
            cleaned_data = form.cleaned_data
            text = cleaned_data.get('text',None)
            to_user = GUser.object.get(uuid_id=uuid_id)
            data_item = ChatMessage(content=text,user=to_user)
            data_item.save()
            message_code = 1
            message = 'Uğurlu'
        else:
            message = " , ".join([v[0].__unicode__() for k, v in form.errors.items()])

        data = {
            'code':message_code,
            'result':message,
        }
        return JsonResponse(data=data)

    else:
        raise Http404



def get_comments(request,uuid_id):
    now = datetime.datetime.now()
    user = request.user
    context = base_auth(req=request)

    if request.method == 'POST' and request.is_ajax():
        try:
            page_num = int(request.POST.get('post-page-num', 1))
        except:
            page_num = 0
        try:
            loaded_post_count = int(request.POST.get('loaded-post-count', 1))
        except:
            loaded_post_count = 0
        obj, created    = Thread.objects.get_or_new(request.user, uuid_id)
        if obj == None:
            raise Http404
        posts = ChatMessage.objects.filter(thread=obj).order_by('-id')

        posts = posts[50 * (page_num - 1) + loaded_post_count:50 * page_num + loaded_post_count]
        list_html = ''
        last_item  = None
        for_i = 0
        for item in posts:
            if for_i == 0 and page_num == 1:
                last_item = item
            for_i +=1
            list_html = "{}{}".format(render_to_string(
                "chat/include/message-text-item.html",
                {
                    "chat": item,
                    "base_profile": request.user,
                }),list_html)
        data = {
            'main_result':list_html,
            'date_time':last_item.id if last_item else 0,
            # 'date_time':posts.first().timestamp.strftime("%d/%m/%Y, %H:%M:%S") if posts else '',
        }
        return JsonResponse(data=data)
    else:
        raise Http404





def get_comments_renew(request,uuid_id):
    now = datetime.datetime.now()
    user = request.user

    if request.method == 'POST' and request.is_ajax():
        list_html = ''
        date_time = ''
        extra_count = 0
        try:
            try:
                date_time = int(request.POST.get('date_time', 1))
            except:
                date_time = -1
            obj, created    = Thread.objects.get_or_new(user, uuid_id)
            if obj == None:
                raise Http404
            posts = ChatMessage.objects.filter(thread=obj).filter(id__gt=date_time).order_by('-id')
            last_item = None
            for_i = 0
            if posts:
                code = 1
                extra_count = posts.count()
                for item in posts:
                    if for_i == 0:
                        last_item = item
                    for_i += 1
                    list_html = "{}{}".format(render_to_string(
                        "chat/include/message-text-item.html",
                        {
                            "chat": item,
                            "base_profile": request.user,
                        }),list_html)
                date_time = last_item.id
                # date_time = posts.first().timestamp.strftime("%d/%m/%Y, %H:%M:%S") if posts else ''
            else:
                code = 2
        except:
            code = 0
        data = {
            'main_result':list_html,
            'date_time':date_time,
            'extra_count':extra_count,
            'code':code,
        }
        return JsonResponse(data=data)
    else:
        raise Http404

templates/chat/css.html
<!-- Bootstrap CSS -->
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css">

templates/chat/inbox.html
{% extends "main-base.html" %}
{% load static %}
{% block css_block %}
<style>
 #message-box-list li:first-child {
    border-bottom: 1px solid #ccc;
    border-top: 1px solid #ccc;
 }
 #message-box-list li {
    border-bottom: 1px solid #ccc;
    padding: 10px;
    cursor: pointer;
 }
 #message-box-list li:hover {
    background: #38a9ff2e;
 }
.ui-block-content {
    padding: 10px;
}
#message-box-search .form-group {
    position: relative;
    margin-bottom: 0;
}
#message-box-search .form-control {
    border: 1px solid #94969a;
}
@media (min-width: 1024px) {
    #ui-block-content{
        padding: 0 180px;
    }
}
.messae-deatil-general{
    border-radius: 36px;
    padding: 15px 25px !important;
    margin: 15px;
}
.messae-deatil-other{
    background: rgba(63, 66, 87, 0.15);
}
.messae-deatil-me{
    background: #0085ff;
}
.messae-deatil-me a , .messae-deatil-me .chat-message-item , .messae-deatil-me .notification-date {
    color: #fff;
}
.chat-field textarea {
    border: 1px solid #b7aeae;
}
</style>
{% endblock %}
{% block content_block %}


<div class="container-fluid">
	<div class="row">
		<div class="col col-xl-12 order-xl-12 col-lg-12 order-lg-2 col-md-12 order-md-1 col-sm-12 col-12">
			<div class="ui-block">
				<div class="row">
					<div class="col col-xl-5 col-lg-6 col-md-12 col-sm-12 col-12 padding-r-0">
                        <div class="ui-block">
                            <div class="ui-block-title">
                                <h6 class="title">Mesajlarınız</h6>
                                <a class="more"><svg class="olymp-three-dots-icon"><use xlink:href="{% static 'local/app/svg-icons/sprites/icons.svg' %}#olymp-three-dots-icon"></use></svg></a>
                            </div>
                            <div class="ui-block-content">
                                <form id="message-box-search">
                                    {% csrf_token %}
                                    <input type="hidden" name="page-num-message-box" id="page-num-message-box" value="1"/>
                                    {{ message_box_form.search_text }}
                                </form>
                            </div>
                        </div>
						<!-- Notification List Chat Messages -->
						<ul class="notification-list chat-message" id="message-box-list">
						</ul>

						<!-- ... end Notification List Chat Messages -->


					</div>

					<div class="col col-xl-7 col-lg-6 col-md-12 col-sm-12 col-12 padding-l-0">


						<!-- Chat Field -->
                        {% if object %}

                <form id="main-post-search-form">{% csrf_token %}
                    <input type="hidden" id="post-page-num" name="post-page-num" value="1"/>
                    <input type="hidden" id="loaded-post-count" name="loaded-post-count" value="0"/>
                    <input type="hidden" id="date_time" name="date_time" value=""/>
                </form>
						<div class="chat-field">
							<div class="ui-block-title">
								<h6 class="title">{% if user != object.first %}{{ object.first }}{% else %}{{ object.second }}{% endif %}</h6>
								<a href="#" class="more"><svg class="olymp-three-dots-icon"><use xlink:href="{% static 'local/app/svg-icons/sprites/icons.svg' %}#olymp-three-dots-icon"></use></svg></a>
							</div>
							<div class="mCustomScrollbar" data-mcs-theme="dark" id="message-datil-list">

								<ul class="notification-list chat-message chat-message-field" id="post-grid-list">


								</ul>
							</div>

							<form id="main-post-form-data" method="post">
                                {% csrf_token %}
								<div class="form-group">
                                    {{ form.message }}
								</div>
								<div class="add-options-message">
									<a href="#" class="options-message">
										<svg class="olymp-computer-icon"><use xlink:href="{% static 'local/app/svg-icons/sprites/icons.svg' %}#olymp-computer-icon"></use></svg>
									</a>
									<button type="submit" class="btn btn-primary btn-sm">Göndər</button>
								</div>

							</form>

						</div>
                        {% else %}
                        <div class="ui-block">
                            <div class="ui-block-content text-center" id="ui-block-content">
                                <img class="img-responsive" src="{% static 'local/app/img/message-note.png' %}" alt="error_500">
                                <div class="crumina-module crumina-heading">
                                </div>
                            </div>
                        </div>
                        {% endif %}
						<!-- ... end Chat Field -->

					</div>
				</div>
			</div>
		</div>

	</div>
</div>


{% endblock %}

{% block js_block %}

<script>
    $('#message-datil-list').scroll(function () {

        //- 10 = desired pixel distance from the bottom of the page while scrolling)
        if ($('#message-datil-list').scrollTop() == 100) {
        }
    });
</script>


        <script type="text/javascript">
        $("#message-box-search").submit(function(e){
            {#mb_searchForm();#}
            return false;
        });
        $( "#message-box-search :input" ).keyup(function(event) {
            var keycode = (event.keyCode ? event.keyCode : event.which);
            if(keycode == '13'){
                mb_searchForm();
            }
        });
    </script>


    <script>
        var mb_search_form = $('#message-box-search');
        var mb_main_data_content_data = $('#message-box-list');
        var mb_is_active = true;
        var mb_has_data = true;
            $('#message-box-list').on('scroll', function() {
                if ($(this).scrollTop() +
                    $(this).height()>=
                    ($(this).height() + 250) && mb_is_active && mb_has_data) {
                    mb_infinityForm();
                    // alert('End of DIV is reached!');
                }
            });

        function mb_infinityForm() {
            mb_is_active = false;
              $.post("{% url 'chat:message-box-list' %}",mb_search_form.serialize())
                  .done(function (result) {
                      $('#message-box-list').append(result['main_result']);
                      if(result['main_result'] != ''){
                          $('#page-num-message-box').val(parseInt($('#page-num-message-box').val()) + 1);
                      }else{
                          mb_has_data = false;
                      }
                      mb_is_active = true;

                      console.log(result)
                }).fail(function () {
                    mb_is_active = true;
              });
         }
    </script>


    <script>
        var mb_search_form = $('#message-box-search');


        $( document ).ready(function() {
            setTimeout(function(){
                mb_searchForm();
            }, 500);
            console.log( "ready!" );
        });

        function mb_searchForm() {
            $('#page-num-message-box').val(1);
            mb_main_data_content_data.html('<a id="load-more-button" href="#" class="btn btn-control btn-more" data-load-link="items-to-load.html" data-container="newsfeed-items-grid"><svg class="olymp-three-dots-icon"><use xlink:href="{% static 'local/app/svg-icons/sprites/icons.svg' %}#olymp-three-dots-icon"></use></svg></a>');
          $.post("{% url 'chat:message-box-list' %}",mb_search_form.serialize())
              .done(function (result) {
                  mb_main_data_content_data.html(result['main_result']);
                  $('#page-num-message-box').val(2);

            }).fail(function () {
                  mb_main_data_content_data.html('');
          });
        }


    </script>

    {% if object %}
        <script>
            post_share_url = '';
            var data_v_change = '';
            {% if user != object.first %}
                data_v_change = '{% url 'chat:get-comments-renew-list' object.second.uuid_id %}';
                comment_data_get_url = '{% url 'chat:get-comments-list' object.first.uuid_id %}';
            {% else %}
                data_v_change = '{% url 'chat:get-comments-renew-list' object.second.uuid_id %}';
                comment_data_get_url = '{% url 'chat:get-comments-list' object.second.uuid_id %}';
            {% endif %}

        </script>

        {% include 'chat/include/js.html' %}
    {% endif %}
{% endblock %}

templates/chat/js.html
 <!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script
  src="//code.jquery.com/jquery-3.3.1.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"></script>
<script src="//stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>

templates/chat/thread.html
{% extends "main-base.html" %}

{% block content_block %}
<h3>Thread for {% if user != object.first %}{{ object.first }}{% else %}{{ object.second }}{% endif %}</h3>
<ul id='chat-items'>
{% for chat in object.chatmessage_set.all %}

<li>{{ chat.message }} via {{ chat.user }}</li>

{% endfor %}
</ul>

<form id='form' method='POST'> {% csrf_token %}
{{form.as_p }}
<input type='submit' class='btn btn-primary'/>
</form>

{% endblock %}

{% block script %}

<script>
$(document).ready(function(){
    // alert("jquery world")
    var formData = $("#form")
    var messageInput = $("#id_message")
    var chatItems = $('#chat-items')
    var loc = window.location
    var wsStart = "ws://"
    if (loc.protocol == "https:"){
        wsStart = "wss://"
    }
    var webSocketEndpoint =  wsStart + loc.host + loc.pathname  // ws : wss
    var socket = new WebSocket(webSocketEndpoint)
    socket.onmessage = function(e){
        console.log('message', e)
        // alert(e.data)
        var msgData = JSON.parse(e.data)
        console.log(msgData)
        chatItems.append('<li>${msgData.msg} via ${msgData.user}</li>')
    }
    socket.onopen = function(e){
        console.log('open', e)
        formData.submit(function(event){
            event.preventDefault()
            var messageText = messageInput.val()
            console.log(messageText)
            var jsonData = JSON.stringify({msg: messageText, user:'{{ request.user.username }}'})
            socket.send(jsonData)
            formData[0].reset()
        })
    }
    socket.onerror = function(e){
        console.log('error', e)
    }
    socket.onclose = function(e){
        console.log('closed', e)
    }
    if (socket.readyState == WebSocket.OPEN) {
    } else if (socket.readyState == WebSocket.CONNECTING){
        console.log("connecting..")
    }
})
</script>
{% endblock %}