chat/urls.py
from django.urls import path, re_path


from .views import ThreadView, inbox_view, message_box_list, get_comments, get_comments_renew

app_name = 'chat'
urlpatterns = [
    path("", inbox_view, name='inbox'),
    path("message-box-list", message_box_list, name='message-box-list'),
    path("get-comments-list/<uuid_id>",get_comments,name='get-comments-list'),
    path("get-comments-list-renew/<uuid_id>",get_comments_renew,name='get-comments-renew-list'),
    re_path(r"^(?P<uuid_id>[\w.@+-]+)", ThreadView.as_view(),name='message-box-detail'),
    # re_path(r"^get-comments-list/(?P<uuid_id>[\w.@+-]+)", get_comments,name='get-comments-list'),
]

userprofile/urls.py
from django.urls import path

from userprofile.views import *

app_name = 'userprofile'

urlpatterns = [
	path('', feed, name='feed'),
	path('', feed, name='dashboard'),
	path('photo-upload/', photo_upload, name='photo-upload'),
	path('page/<slug>/', staticpage_detail, name='static-page-detail'),
	path('get-photo-profile/<type>/', get_photo_profile, name='get-photo-profile'),
	# path('profile/', profile, name='profile'),
	# path('profile/<slug>', profile_tab, name='profile-tab'),
	path('v/<id>/', profile_v, name='profile-v'),
	path('v/<id>/change/', profile_v_change, name='profile-v-change'),
	path('general-post-change/', general_post_change, name='general-post-change'),
	path('v/<id>/<slug>', profile_tab, name='profile-tab-v'),
	path('settings/<slug>', settings_page, name='settings'),
	path('experience-andeducation-create/<slug>', experience_andeducation_create, name='experience-andeducation-create'),
	path('experience-andeducation-list/<slug>', experience_andeducation_list, name='experience-andeducation-list'),
	path('post-share/', post_share, name='post-share'),
	path('post-remove/<id>/', post_remove, name='post-remove'),

	path('like-save/<int:id>/<slug>/', like_save, name='like-save-post'),



	path('friend-list/<slug>', friend_list, name='friend-list'),
	# path('projects-form/', projects_form, name='projects-form'),
	path('notifications-list/', notifications_list, name='notifications-list'),
	path('message-notification-show/<slug>/', message_notification_show, name='message-notification-show'),
	path('notification-remove/<id>/', notification_remove, name='notification-remove'),
	path('users-list/', users_list, name='users-list'),
	path('event-list/<slug>/', event_list, name='event-list'),
	path('news-list/<slug>/', blognews_list, name='blognews-list'),
	path('friend-list/<slug>/', friend_list, name='friend-list'),
	path('all-sections/', all_sections, name='all-sections'),
	path('all-sections/section-<int:id>/', section_item, name='section-item'),
	path('all-sections/section-<int:id>/parent-<int:p_id>/', tutorials, name='section-item-parent'),
	path('all-sections/tutorial-<int:id>/', article_item, name='tutorial-item'),

	path('projects-list/', projects_list, name='projects-list'),
	path('projects/create/', projects_create, name='projects-create'),
	path('projects/edit/<int:id>/', projects_edit, name='projects-edit'),
	path('projects/view/<int:id>/', projects_view, name='projects-view'),

	path('events-list/', events_list, name='events-list'),
	path('events/view/<int:id>/', events_view, name='events-view'),
	path('news-list/', news_list, name='news-list'),
	path('news/edit/<int:id>/', projects_edit, name='news-view'),


 ]

templates/home/include/post/post-item.html
{% load i18n %}
{% load static %}
<div class="ui-block all-post-item-{{ item.id }}">

    <article class="hentry post has-post-thumbnail">

        <div class="post__author author vcard inline-items">
            <img src="{% if base_profile.profile_picture %}{{ base_profile.profile_picture.url }}{% else %}{% static 'local/app/img/default-user.jpg' %}{% endif %}" style="height: 40px;" alt="author">

            <div class="author-date">
                <a class="h6 post__author-name fn" href="{% url 'userprofile:profile-v' item.user.uuid_id %}">{{ item.user.get_full_name }}</a>
                <div class="post__date">
                    <time class="published" datetime="{{ item.created_date|date:'Y-m-dTH:i' }}">
                        {{ item.created_date }}
                    </time>
                </div>
            </div>

{#            <div class="more">#}
{#                {% if me %}#}
{#                    <a href="javascript:void(0)" onclick="removePost('{% url 'userprofile:post-remove' item.id %}','{{ item.id }}')">#}
{#                        <svg class="olymp-little-delete" style="height: 11px;width: 11px;"><use xlink:href="{% static 'local/app/svg-icons/sprites/icons.svg' %}#olymp-little-delete"></use></svg>#}
{#                    </a>#}
{#                {% endif %}#}
{#                <svg class="olymp-three-dots-icon"><use xlink:href="{% static 'local/app/svg-icons/sprites/icons.svg' %}#olymp-three-dots-icon"></use></svg>#}
{#                <ul class="more-dropdown">#}
{#                    <li>#}
{#                        <a href="#">Edit Post</a>#}
{#                    </li>#}
{#                    <li>#}
{#                        <a href="javascript:void(0)" onclick="removePost('{% url 'userprofile:post-remove' item.id %}','{{ item.id }}')">Sil</a>#}
{#                    </li>#}
{#                    <li>#}
{#                        <a href="#">Turn Off Notifications</a>#}
{#                    </li>#}
{#                    <li>#}
{#                        <a href="#">Select as Featured</a>#}
{#                    </li>#}
{#                </ul>#}
{#            </div>#}

        </div>

        <p class="post-item-content">
            {{ item.content }}
        </p>

{#        <div class="post-thumb">#}
{#            <img src="{% static 'local/app/img/post__thumb1.jpg' %}" alt="photo">#}
{#        </div>#}

        <div class="post-additional-info inline-items">

            <a href="javascript:void(0)" class="post-add-icon inline-items liked-icon-{{ item.id }} {% if post_liked %} did-it-icon {% endif %}" onclick="postSaveLike('{% url 'userprofile:like-save-post' item.id 'liked' %}','{{ item.id }}','liked')">
                <svg class="olymp-heart-icon"><use xlink:href="{% static 'local/app/svg-icons/sprites/icons.svg' %}#olymp-heart-icon"></use></svg>
                <span id="liked-count-{{ item.id }}">{{ item.liked_count }}</span>
            </a>

{#            <div class="names-people-likes">#}
{#                <a href="#">Jimmy</a>, <a href="#">Andrea</a> and#}
{#                <br>47 more liked this#}
{#            </div>#}


            <div class="comments-shared">
                <a href="javascript:void(0)" class="post-add-icon inline-items">
                    <svg class="olymp-speech-balloon-icon"><use xlink:href="{% static 'local/app/svg-icons/sprites/icons.svg' %}#olymp-speech-balloon-icon"></use></svg>
                    <span id="saved-count-{{ item.id }}">{{ item.saved_count }}</span>
                </a>
            </div>


        </div>

        <div class="control-block-button post-control-button">

            <a href="javascript:void(0)" class="btn btn-control liked-button-{{ item.id }} {% if post_liked %} did-it {% endif %}" onclick="postSaveLike('{% url 'userprofile:like-save-post' item.id 'liked' %}','{{ item.id }}','liked')">
                <svg class="olymp-like-post-icon"><use xlink:href="{% static 'local/app/svg-icons/sprites/icons.svg' %}#olymp-like-post-icon"></use></svg>
            </a>

            <a href="javascript:void(0)" class="btn btn-control saved-button" onclick="">
                <svg class="olymp-comments-post-icon"><use xlink:href="{% static 'local/app/svg-icons/sprites/icons.svg' %}#olymp-comments-post-icon"></use></svg>
            </a>
            {% if me %}
                <a href="javascript:void(0)" class="btn btn-control saved-button" onclick="removePost('{% url 'userprofile:post-remove' item.id %}','{{ item.id }}')">
                    <svg class="olymp-little-delete"><use xlink:href="{% static 'local/app/svg-icons/sprites/icons.svg' %}#olymp-little-delete"></use></svg>
                </a>
            {% endif %}

        </div>

    </article>
</div>